### ISSUE TITLE
Doesn't work while logged out

### ISSUE THREAD

**Issue by odie5533** [splttingatms/YouTubeDefaultSpeed#2]
I noticed the script doesn't work if you aren't logged in to YouTube because the head element yt-masthead-user doesn't exist. I fixed this by changing the line to: `var head = document.getElementById("yt-masthead-content").previousSibling;` Tested on Firefox and Chrome while logged in and not and seems to work fine.

**Comment by yolorag** [comment]
God bless you ;*
